env:
    global:
        # following Coverity instructions
        # https://scan.coverity.com/travis_ci
        - secure: "fE61u9/Qtn2jXo+ReUFdscmLAYMxOa3Rbvj3LMlRR6dV7tZf6arJJGYxklABKGQi5qMkYgcOY0rUqaOfvo/rPcIKNmlqZ1rz/nBZnvmvG8AKY6rtKKD0TUMphU3IzO2pXW4OywNNEaf8ze1iycB/wpZoBRNcuNev0BRiM8CiExV144abSLZu5vHNXXb9Rnfbn19yQCWdl5cnJlO+m+GQBQDjYCbYIToF6pr2D16qo8PPncYGs2GgdOci4aFs/+nFZS/NHULCafQIGk7tyQg3vq2Tpwi2dTshtfz/Y4JII4DlSFicoer55u2G4ML+9HaufaoFs4aaLROmNrtCbc6WI0upnlsSWlrGsFk2G3UBxopqGoQhmHVi0PYItOhOejz1YEpm4sCSUChrc5DKnmPgL/HXQQ5+/l+3ST9nZn6sZ4fJlwqe57U0e4M1me0hBXHr1t19/g40HAsFVLf7oxP4mpTdFOEF7DceEo5cZYEeiMW5T4gogeWmQjcckTmyHlly0unAyuQKrgCeOsL5Uks6E8TssQMewLp9ZGAMt7W8k7jcmtZpgKYBaf/MQdeICkoGgGg3XJpZSgATGNSzG3IwlNQxjvbteqNfle+kwaurgUGQT8KCnkrvRGvhPwJ0EkOxLj7wb7Ngrni4vldv9Uh9jQ5CWw2i7m/UN0pYV1Klb4Q="

language: cpp

os: linux

dist: trusty

compiler: gcc

sudo: required

before_install:
    # C++14
    # https://github.com/richelbilderbeek/travis_cmake_gcc_cpp14/blob/master/.travis.yml
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - echo "Hello from before_install of gcc build"
      # following Coverity instructions
      # https://scan.coverity.com/travis_ci
    - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install:
    # C++14
    # https://github.com/richelbilderbeek/travis_cmake_gcc_cpp14/blob/master/.travis.yml
    - sudo apt-get install -qq gcc-5 g++-5
    - sudo apt-get update -qq
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

addons:
    # following Coverity instructions
    # https://scan.coverity.com/travis_ci
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - cmake
            - git
            - libx11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libsfml-dev
            - libxcursor-dev
            - libxrandr-dev
            - libxext-dev
            - libxi-dev
            - libxinerama-dev
            - make
    coverity_scan:
        project:
            name: "nrz/ylikuutio"
            description: "Ylikuutio 3D engine. Build submitted via Travis CI"
            notification_email: antti.nuortimo@gmail.com
        build_command_prepend: "mkdir build_coverity && cd build_coverity && cmake .."
        build_command: "make -j 4"
            # https://scan.coverity.com/faq#frequency
        branch_pattern: coverity_scan

script:
    - gcc -v && g++ -v && cmake --version
    - mkdir build_gcc
    - cd build_gcc
    - cmake ..
    - make -j 4
    - ./unit_tests_with_google_test
