language: cpp
dist: trusty
sudo: required
script: mkdir build && cd build && cmake .. && make
matrix:
    include:
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-4.9
                      - cmake
                      - make
                      - libgl1-mesa-dev
                      - libglu1-mesa-dev
                      - libxcursor-dev
                      - libxrandr-dev
                      - libxext-dev
                      - libxi-dev
                      - libxinerama-dev
                      - g++-mingw-w64
                      - gcc-mingw-w64
                      - binutils-mingw-w64
                  env:
                      - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-5
                      - cmake
                      - make
                      - libgl1-mesa-dev
                      - libglu1-mesa-dev
                      - libxcursor-dev
                      - libxrandr-dev
                      - libxext-dev
                      - libxi-dev
                      - libxinerama-dev
                      - g++-mingw-w64
                      - gcc-mingw-w64
                      - binutils-mingw-w64
                  env:
                      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-6
                      - cmake
                      - make
                      - libgl1-mesa-dev
                      - libglu1-mesa-dev
                      - libxcursor-dev
                      - libxrandr-dev
                      - libxext-dev
                      - libxi-dev
                      - libxinerama-dev
                      - g++-mingw-w64
                      - gcc-mingw-w64
                      - binutils-mingw-w64
                  env:
                      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-7
                      - cmake
                      - make
                      - libgl1-mesa-dev
                      - libglu1-mesa-dev
                      - libxcursor-dev
                      - libxrandr-dev
                      - libxext-dev
                      - libxi-dev
                      - libxinerama-dev
                      - g++-mingw-w64
                      - gcc-mingw-w64
                      - binutils-mingw-w64
                  env:
                      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-precise-3.6
                  packages:
                      - clang-3.6
                      - cmake
                      - make
                      - libgl1-mesa-dev
                      - libglu1-mesa-dev
                      - libxcursor-dev
                      - libxrandr-dev
                      - libxext-dev
                      - libxi-dev
                      - libxinerama-dev
                      - g++-mingw-w64
                      - gcc-mingw-w64
                      - binutils-mingw-w64
                  env:
                      - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"

        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-precise-3.7
                  packages:
                      - clang-3.7
                      - cmake
                      - make
                      - libgl1-mesa-dev
                      - libglu1-mesa-dev
                      - libxcursor-dev
                      - libxrandr-dev
                      - libxext-dev
                      - libxi-dev
                      - libxinerama-dev
                      - g++-mingw-w64
                      - gcc-mingw-w64
                      - binutils-mingw-w64
                  env:
                      - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"

        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-precise-3.8
                  packages:
                      - clang-3.8
                      - cmake
                      - make
                      - libgl1-mesa-dev
                      - libglu1-mesa-dev
                      - libxcursor-dev
                      - libxrandr-dev
                      - libxext-dev
                      - libxi-dev
                      - libxinerama-dev
                      - g++-mingw-w64
                      - gcc-mingw-w64
                      - binutils-mingw-w64
                  env:
                      - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"

        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-precise-3.9
                  packages:
                      - clang-3.9
                      - cmake
                      - make
                      - libgl1-mesa-dev
                      - libglu1-mesa-dev
                      - libxcursor-dev
                      - libxrandr-dev
                      - libxext-dev
                      - libxi-dev
                      - libxinerama-dev
                      - g++-mingw-w64
                      - gcc-mingw-w64
                      - binutils-mingw-w64
                  env:
                      - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"

        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-precise-4.0
                  packages:
                      - clang-4.0
                      - cmake
                      - make
                      - libgl1-mesa-dev
                      - libglu1-mesa-dev
                      - libxcursor-dev
                      - libxrandr-dev
                      - libxext-dev
                      - libxi-dev
                      - libxinerama-dev
                      - g++-mingw-w64
                      - gcc-mingw-w64
                      - binutils-mingw-w64
                  env:
                      - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-precise-5.0
                  packages:
                      - clang-5.0
                      - cmake
                      - make
                      - libgl1-mesa-dev
                      - libglu1-mesa-dev
                      - libxcursor-dev
                      - libxrandr-dev
                      - libxext-dev
                      - libxi-dev
                      - libxinerama-dev
                      - g++-mingw-w64
                      - gcc-mingw-w64
                      - binutils-mingw-w64
                  env:
                      - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"
