language: cpp
dist: trusty
sudo: required
script:
    - ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
    - ln -s /usr/bin/g++-7 /usr/local/bin/g++
    - export CC=/usr/bin/gcc-7
    - export CXX=/usr/bin/g++-7
    - gcc -v && g++ -v && cmake --version
    - mkdir build && cd build && cmake .. && make
matrix:
    include:
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-7
                      - cmake
                      - make
                      - libgl1-mesa-dev
                      - libglu1-mesa-dev
                      - libxcursor-dev
                      - libxrandr-dev
                      - libxext-dev
                      - libxi-dev
                      - libxinerama-dev
                      - g++-mingw-w64
                      - gcc-mingw-w64
                      - binutils-mingw-w64
                  env:
                      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - clang-5.0
                      - cmake
                      - make
                      - libgl1-mesa-dev
                      - libglu1-mesa-dev
                      - libxcursor-dev
                      - libxrandr-dev
                      - libxext-dev
                      - libxi-dev
                      - libxinerama-dev
                      - g++-mingw-w64
                      - gcc-mingw-w64
                      - binutils-mingw-w64
                  env:
                      - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"
