matrix:
    include:
        - os:
            - linux
          language: cpp
          dist: trusty
          compiler:
              - gcc
              - clang
          sudo: required
          before_install:
              # C++14
              # https://github.com/richelbilderbeek/travis_cmake_gcc_cpp14/blob/master/.travis.yml
              - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
              - sudo apt-get update -qq
          install:
              # C++14
              # https://github.com/richelbilderbeek/travis_cmake_gcc_cpp14/blob/master/.travis.yml
              - sudo apt-get install -qq gcc-5 g++-5
              - sudo apt-get update -qq
              - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
              - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
          script:
              - gcc -v && g++ -v && cmake --version
              - mkdir build
              - cd build
              - cmake ..
              - make
              - ./unit_tests_with_Google_Test
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - cmake
                      - git
                      - libx11-dev
                      - libgl1-mesa-dev
                      - libglu1-mesa-dev
                      - libxcursor-dev
                      - libxrandr-dev
                      - libxext-dev
                      - libxi-dev
                      - libxinerama-dev
                      - make
