image:
    - Visual Studio 2017

branches:
    only:
        - master

clone_folder: c:\projects\ylikuutio

clone_depth: 5

version: 0.0.3.{build}

platform:
    - x64

configuration:
    - Release
    - Debug

init:
    - set generator="Visual Studio 15 2017 Win64"
    - echo %generator%

before_build:
    - dir
    - cmake --version
    - cmake -DGTEST_HAS_TR1_TUPLE=0 -DDO_UNIT_TESTS_WITH_GOOGLE_TEST=true -G %generator%

build:
    project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
    verbosity: minimal
    parallel: true

test_script:
    - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\unit_tests_with_googletest.exe'
